### ISSUE TITLE
Source of cairo-color-glyphs.patch?

### ISSUE THREAD

**Issue by abbradar** [archfan/infinality_bundle#1]
Hi,

I'm looking towards adopting your updated Infinality patches for use in [NixOS](https://nixos.org). Looking through Cairo patches, most of them are taken from [fontconfig-ultimate repo](https://github.com/bohoomil/fontconfig-ultimate/tree/master/cairo) but one, "cairo-color-glyphs.patch", is new. Where did it come from and what does it do?

**Comment by archfan** [comment]
Hi

the patch is not exactly new. It's just that the Cairo PKGBUILD revision 
you were looking at is slightly outdated. Bohoomil has multiple branches 
and the branch "pkgbuild" features the latest version including this 
exact patch. That's also where I got it from. This said patch enables 
support for color glyphs.

Here's the link: 
https://github.com/bohoomil/fontconfig-ultimate/tree/pkgbuild/03_cairo-iu

I hope this will help you.

Cheers

**Comment by abbradar** [comment]
Thank you very much! Yes, that's what I looked for.
