### ISSUE TITLE
freetype 2.8?

### ISSUE THREAD

**Issue by SolarAquarion** [archfan/infinality_bundle#10]

**Comment by SolarAquarion** [comment]
Hunk #2 FAILED at 364.
1 out of 2 hunks FAILED -- saving rejects to file src/base/ftinit.c.rej
patching file src/base/ftlcdfil.c
Hunk #2 FAILED at 310.
1 out of 2 hunks FAILED -- saving rejects to file src/base/ftlcdfil.c.rej
patching file src/base/ftobjs.c
Hunk #1 succeeded at 43 (offset 3 lines).
Hunk #2 succeeded at 83 (offset 3 lines).
Hunk #3 succeeded at 574 (offset 4 lines).
Hunk #4 succeeded at 651 (offset 4 lines).
Hunk #5 succeeded at 753 (offset 4 lines).
Hunk #6 succeeded at 810 (offset 4 lines).
Hunk #7 succeeded at 5046 (offset 112 lines).
patching file src/base/ftoutln.c
patching file src/base/ftsynth.c
patching file src/base/Jamfile
patching file src/base/rules.mk
patching file src/cff/cffobjs.c
Hunk #1 succeeded at 39 (offset 5 lines).
Hunk #2 succeeded at 1175 (offset -1 lines).
patching file src/smooth/ftsmooth.c
Hunk #3 succeeded at 2328 with fuzz 2.
Hunk #4 succeeded at 2554 (offset 54 lines).
Hunk #5 succeeded at 2676 with fuzz 2 (offset 54 lines).
Hunk #6 FAILED at 2654.
Hunk #7 succeeded at 2740 (offset 49 lines).
Hunk #8 succeeded at 2763 (offset 49 lines).
Hunk #9 succeeded at 2770 (offset 49 lines).
Hunk #10 FAILED at 2766.
Hunk #11 succeeded at 2875 (offset 49 lines).
Hunk #12 succeeded at 2896 (offset 49 lines).
2 out of 12 hunks FAILED -- saving rejects to file src/smooth/ftsmooth.c.rej
patching file src/truetype/ttinterp.c
Hunk #1 succeeded at 5753 (offset 14 lines).

**Comment by SolarAquarion** [comment]
@archfan the PKGBUILD hasn't been updated @djpohly 

/home/solaraquarion/infinality_bundle/01_freetype2-iu/src/freetype2/src/base/ftinit.c:47:10: fatal error: ftinf.h: No such file or directory
 #include "ftinf.h"
          ^~~~~~~~~
compilation terminated.
make: *** [/home/solaraquarion/infinality_bundle/01_freetype2-iu/src/freetype2/builds/freetype.mk:246: /home/solaraquarion/infinality_bundle/01_freetype2-iu/src/freetype2/objs/ftinit.lo] Error 1
==> ERROR: A failure occurred in buid

**Comment by igrekster** [comment]
I'm using custom settings, and with this patch the fonts look really dirty and thick. I had to revert to 2.7.1.
Is there any special environment variable I need to set for this patch?
```shell
INFINALITY_FT_FILTER_PARAMS="11 22 38 22 11"
INFINALITY_FT_GRAYSCALE_FILTER_STRENGTH=0
INFINALITY_FT_FRINGE_FILTER_STRENGTH=0
INFINALITY_FT_AUTOHINT_HORIZONTAL_STEM_DARKEN_STRENGTH=10
INFINALITY_FT_AUTOHINT_VERTICAL_STEM_DARKEN_STRENGTH=25
INFINALITY_FT_WINDOWS_STYLE_SHARPENING_STRENGTH=0
INFINALITY_FT_CHROMEOS_STYLE_SHARPENING_STRENGTH=0
INFINALITY_FT_STEM_ALIGNMENT_STRENGTH=100
INFINALITY_FT_STEM_FITTING_STRENGTH=100
INFINALITY_FT_GAMMA_CORRECTION="0 100"
INFINALITY_FT_BRIGHTNESS="0"
INFINALITY_FT_CONTRAST="0"
INFINALITY_FT_USE_VARIOUS_TWEAKS=true
INFINALITY_FT_AUTOHINT_INCREASE_GLYPH_HEIGHTS=true
INFINALITY_FT_AUTOHINT_SNAP_STEM_HEIGHT=100
INFINALITY_FT_STEM_SNAPPING_SLIDING_SCALE=0
INFINALITY_FT_USE_KNOWN_SETTINGS_ON_SELECTED_FONTS=true

INFINALITY_FT_GLOBAL_EMBOLDEN_X_VALUE=0
INFINALITY_FT_GLOBAL_EMBOLDEN_Y_VALUE=0
INFINALITY_FT_BOLD_EMBOLDEN_X_VALUE=0
INFINALITY_FT_BOLD_EMBOLDEN_Y_VALUE=0

```

**Comment by djpohly** [comment]
Hm, It may be that something more than simply forward-porting the patches (which is all I did) is needed, or maybe (probably?) I missed something.  I'll take another look.

**Comment by SolarAquarion** [comment]
You should check the
https://aur.archlinux.org/cgit/aur.git/tree/0003-inf.patch?h=freetype2-infinality-ultimate
proper inf patches which generates new files

**Comment by igrekster** [comment]
The updated patch from @djpohly (#12) is working fine for me.
