### ISSUE TITLE
FreeType 2.9

### ISSUE THREAD

**Issue by kq01526** [archfan/infinality_bundle#17]
@archfan Can you please update to FreeType 2.8.1?

It has some font rendering improvements: https://www.freetype.org/index.html#news

**Comment by RJVB** [comment]
src/smooth/ftsmooth.c is the only file where the 2.8 patch no longer applies, but probably also the cornerstone of the whole enterprise.
I had a quick look, part of the reason why the patch is broken is that the new ftsmooth.c already includes a number of functions that used to be introduced by the patch.

Has anyone tried NOT patching this file and comparing the result with 2.8(.0)?

**Comment by RJVB** [comment]
2.8 with the existing patch, 2.8.1 ditto but ftsmooth.c unpatched

autohinter off:
![2 8-vs-2 8 1-auto-off](https://user-images.githubusercontent.com/1756884/34462902-a7aa3eb8-ee4d-11e7-9326-e4407fc78285.png)

autohinter on:
![2 8-vs-2 8 1-auto-on](https://user-images.githubusercontent.com/1756884/34462905-ad0c4ad6-ee4d-11e7-9796-e159e193e4bc.png)

**Comment by kq01526** [comment]
FreeType 2.9 is available now:

https://www.freetype.org/index.html#news

**Comment by kq01526** [comment]
@archfan @RJVB Any update on this one?

**Comment by RJVB** [comment]
>@archfan @RJVB Any update on this one?

Not from me, I'm still testing 2.8.1 .

R.

**Comment by kq01526** [comment]
> @RJVB wrote:
> Not from me, I'm still testing 2.8.1 .

2.9 is available now :wink:.

**Comment by RJVB** [comment]
I got that, but I'm not one to fix things that ain't broken. Does 2.9 introduce an official fix for the lineheight increase that was introduced in 2.8?

**Comment by fitojb** [comment]
> Does 2.9 introduce an official fix for the lineheight increase that was introduced in 2.8?

Bugs that aren’t reported can’t get fixed… I don’t see anything related to line height [here](https://savannah.nongnu.org/bugs/?group=freetype) :)

**Comment by RJVB** [comment]
They sometimes do get fixed because they're detected internally, but bugs that never get fixed are those that are not recognised as such by the developers.

And I fear that's exactly what we have here, a case of "works as intended". "They" even provided at least 1 workaround to be applied to your own code...

**Comment by igrekster** [comment]
While the builtin rendering in 2.9 is quite decent, my favourite Fira Code was not as good as it was with Infinality. There is a bounty  on this issue and a developer interested in porting the patches to 2.9, but we are a bit short on funding. https://www.bountysource.com/issues/53252500-freetype-2-9
