### ISSUE TITLE
freetype-2.7.1 released

### ISSUE THREAD

**Issue by KalelCooper** [archfan/infinality_bundle#4]

**Comment by kokoko3k** [comment]
Yes, pleease!

**Comment by archfan** [comment]
Alright, alright. I'm on it.

**Comment by kokoko3k** [comment]
Please try to merge https://github.com/archfan/infinality_bundle/pull/5
It seems to work here:

**Comment by CamilleScholtz** [comment]
Once this is working, could you also create a release please? Thanks!

oh and is there a difference between these patches and https://github.com/julroy67/kagayaki ?

**Comment by archfan** [comment]
Of course I will.

It seems like the difference is that kagayaki doesn't actually use the 
full infinality patchset.


https://git.archlinux.org/svntogit/packages.git/tree/trunk?h=packages/freetype2

https://github.com/julroy67/kagayaki/tree/master/base/freetype2-kagayaki


There is little difference between these two.

**Comment by kokoko3k** [comment]
Just installed the prerelease, it is working fine here; hardfbuzz is happy and fonts keep looking great 👍

**Comment by CamilleScholtz** [comment]
https://github.com/6c37/crux-ports-dropin

Updated the CRUX ports I maintain, and everything seems to work nicely!

**Comment by IdiotEbrilo** [comment]
Thanks guys! Everything seems to be working properly, fonts are as nice and clean as they used to be.

**Comment by pdeljanov** [comment]
Thanks! Works great in combination with the instructions in this guide: https://gist.github.com/cryzed/e002e7057435f02cc7894b9e748c5671. 

Kerning looks much improved compared to infinality-bundle as well.
